### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by KexPilot** [off-world/lightdm-tiny-greeter#1]
When using `make` I got a lot of `undefined reference` errors.
After fiddleing and googleing a lot, I discovered that changing the order in the `build` part of the `Makefile` (moving `$(LIBS)` to the end of the line, so that they become the last arguments, not the first) resolved my issue.
Not sure what's happening, didn't look that much into it, but a source that gave me this idea mentions that new gcc versions are more strict about argument order.
I'm quite new to git and github, don't know if this is the apropriate place for this.

**Comment by tobiohlala** [comment]
Thank you for mentioning! I will have a look into this.
