### ISSUE TITLE
Greeter won't start, scarce logging.

### ISSUE THREAD

**Issue by zoefiri** [off-world/lightdm-tiny-greeter#5]
here's the contents of lightdm.log, the seat0 log is supposed to have logging from the greeter right? It's empty so this is all I have, not sure what else I should really report on this. 
My system is Void so no systemd, just runit if that might be an issue.
https://gist.github.com/ZoeFiri/b90c4b40db3444c436e5a826ea1daed6

**Comment by zoefiri** [comment]
Nvm, figured it out. Looks like the xsession desktop entry I specified was malformed, I'm not sure if this is an error in how you're parsing the .desktop or if the .desktop files for my wm were actually messed up (herbstluftwm) but I messed with other wms and,

broken .desktop 
`[Desktop Entry]`
`Encoding=UTF-8`
`Name=Dwm`
`Comment=Dynamic window manager`
`Exec=dwm`
`Icon=dwm`
`Type=XSession`

working .desktop
`[Desktop Entry]`
`Name=herbstluftwm`
`Comment=herbs`
`Exec=/usr/bin/herbstluftwm`
`TryExec=/usr/bin/herbstluftwm`
`Icon=herbstluftwm`
`Type=Application`

two of the .desktop files in my xsessions had the broken format so I don't really know if they were just badly written.

**Comment by tobiohlala** [comment]
Glad you figured it out. If you're interested in which desktop-entry formats are supported I think you should consult the lightdm documentation as the method processing the desktop-entry is `lightdm_greeter_start_session_sync` which is ligthdm code.
