### ISSUE TITLE
Can't start X session

### ISSUE THREAD

**Issue by mmsh1** [off-world/lightdm-tiny-greeter#7]
Hello!
Although usual lightdm works fine, I can't log in with lightdm-tiny-greeter. After every attempt login screen just appear again.
In my /usr/share/xsession I have only:
`bspwm.desktop`
In config.h I have this line:
`static const char *session = "bspwm";`
The only thing I have in my /var/log/lightdm/seat0-greeter.log is:
`** (process:847): WARNING **: 16:51:52.046: Failed to open CK session: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ConsoleKit was not provided by any .service files`
I will appreciate any help.

**Comment by Gameransari** [comment]
> Hello!
> 
> Although usual lightdm works fine, I can't log in with lightdm-tiny-greeter. After every attempt login screen just appear again.
> 
> In my /usr/share/xsession I have only:
> 
> `bspwm.desktop`
> 
> In config.h I have this line:
> 
> `static const char *session = "bspwm";`
> 
> The only thing I have in my /var/log/lightdm/seat0-greeter.log is:
> 
> `** (process:847): WARNING **: 16:51:52.046: Failed to open CK session: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ConsoleKit was not provided by any .service files`
> 
> I will appreciate any help.

**Just one Command Here the Solution... **
https://youtu.be/34iXHWuhsss

**Comment by mmsh1** [comment]
Maybe someone will find it useful. My problem solved after uncommenting string 
`session-wrapper=/etc/lightdm/Xsession`
in lightdm.conf
